# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 80a94feb27c39b5113c4b16469dc6f66bb4ce5c10472352f1a1714fadb0bdfbed200499d18856a10c87d1c8dbca4779b81f8baaf142073d234e1232ba77ec271

test:
  secret_key_base: 937c664d9731308b87a96412e2b156f1c86a2ebfdd11591a72ea8af146ac5b6a3a3f2482ea89c284120520eb18eae8d14becdc61875260d47c8a214c0efcfc11

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
